basket/urls.py
from django.urls import path
from . import views

app_name='basket'

urlpatterns = [
    path('',views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                #new
from django.conf.urls.static import static      #new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/',include('basket.urls', namespace='basket')),
    path('saved/',include('saved.urls', namespace='saved')),
    path('account/',include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__debug__/", include(debug_toolbar.urls)),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saved/urls.py
from django.urls import path
from . import views

app_name='saved'

urlpatterns = [
    path('wishlist/', views.wishlist, name='wishlist'),
    path('saved/', views.add_item, name='saved'),

]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('',views.product_all,name='product_all'),
    path('about/',views.about,name='about'),
    path('subscribe_section/',views.subscribe_section,name='subscribe_section'),
    path('contact/',views.contact_section,name='contact_us'),
    path('new_arrival/',views.new_arrival,name='new_arrival'),   
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    
    
]

store/models.py
from django.conf import settings
from django.db import models
from datetime import datetime
from django.urls import reverse

# Create your models here.

# These are basically instructions for django to create actual tables in the database
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class WishlistManager(models.Manager):
    def get_queryset(self):
        return super(WishlistManager, self).get_queryset().filter(is_wishlisted=True)



class Category(models.Model):
    name = models.CharField(max_length=225,db_index=True)               #db_index-->??
    slug = models.SlugField(max_length=225, unique=True)                #SlugField,unique--->??
    category_image = models.ImageField(upload_to='uploads/ategory', default='uploads/products/default.jpg')

    class Meta:                                                         #Meta-->??
        verbose_name_plural='categories'
    
    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE , related_name='product_creator')
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    brand = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_wishlisted = models.BooleanField(default=False)
    description = models.CharField(
        max_length=1000, default='', blank=True, null=True)
    image = models.ImageField(upload_to='uploads/products/',default='uploads/products/default.jpg')
    image2 = models.ImageField(upload_to='uploads/products/',default='uploads/products/default.jpg')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()
    wishlisted = WishlistManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering=('created',)
    
    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])
    
    def __str__(self):
        return self.title
    
    @staticmethod                                                       #@staticmethod-->??
    def get_products_by_id(ids):
        return Product.objects.filter(id__in=ids)
  
    @staticmethod
    def get_all_products():
        return Product.objects.all()
  
    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Product.objects.filter(category=category_id)
        else:
            return Product.get_all_products()



class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    password = models.CharField(max_length=100)
  
    # to save the data
    def register(self):
        self.save()
  
    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email=email)
        except:
            return False
  
    def isExists(self):
        if Customer.objects.filter(email=self.email):
            return True
        
        return False
    
class Order(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,
                                 on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    address = models.CharField(max_length=50, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    date = models.DateField(default=datetime.today)
    status = models.BooleanField(default=False)
  
    def placeOrder(self):
        self.save()
  
    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(customer=customer_id).order_by('-date')

store/views.py
from django.shortcuts import get_object_or_404,render
from decimal import Decimal

# Create your views here.
from account.models import UserBase
from .models import Category,Product,Order,Customer

def product_all(request):
    products = Product.products.all()          #new
    return render(request, 'store/index.html',{'products':products})


def product_detail(request, slug):
    products_at_discount= get_object_or_404(Product, slug=slug, in_stock=True)
    original= get_object_or_404(Product, slug=slug, in_stock=True)
    try:
        user = UserBase.objects.get(user_name = request.user.user_name)
        if user.is_subscribed:
            result = 'yes' 
            print('yes')
            products_at_discount.price = products_at_discount.price *Decimal(0.9)
        else:
            result = 'no'   
    except:
        result = 'no'
        print(result)
    return render(request,'store/single.html',{'product':products_at_discount,'original':original,'result':result})

def category_list(request, category_slug=None):
    category = get_object_or_404(Category,slug=category_slug)
    products_at_discount = Product.objects.filter(category=category)
    original = Product.objects.filter(category=category)
    try :
        user = UserBase.objects.get(user_name = request.user.user_name)
        if user.is_subscribed:
            result = 'yes'
            for i in products_at_discount:
                i.price = i.price *Decimal(0.9)
        else:
            result = 'no'   
    except:
        result = 'no'
        print(result)
        
    return render(request, 'store/category.html',{'category':category,'original':original, 'products':products_at_discount,'result':result})

def about(request):
    return render(request, 'store/about.html')

def subscribe_section(request):
    return render(request,'store/subscribe_section.html')

def contact_section(request):
    return render(request,'store/contactus.html')

def new_arrival(request):
    return render(request,'store/new_arrivals.html')

templates/store/about.html
{% extends '../base.html' %} {%load static%} {%block content %}

<div id="big-img-div">
  <h2>We are <span class="brand_name about">Modern Classics</span></h2>
</div>
<div class="about-div">
  <p>
    <span class="brand_name">Modern Classics</span> is a website that i (<i
      >Jayesh Khairnar</i
    >) have created as my capstone project while learning django-full stack web
    development. I chose to build an E-commerce store cause the oppurtunities
    and possibilties are endless when it comes to an E-commerce store, as
    there's so much to do and i really got to learn a lot more while working on
    this website than i had while theoretically learning the technologies such
    as django.
  </p>
  <p>
    For the front-end and for overall structure of the website i took
    inspiration from the website <span class="brand_name">ZANEROBE</span>.
    Anyone interested in checking out their website can do so by clcking on the
    link <a href="https://zanerobe.com/" target="_blank">here</a>. So Finally
    thank you for visiting and have a great day.
  </p>
  <p>We are <span class="brand_name">Modern Classics</span></p>
  <img
    id="sml-img-div"
    src="{% static 'images/ZANEROBE-About-NR-2.jpg' %}"
    alt="image"
  />
</div>
{%endblock%}

templates/store/category.html
{% extends "../base.html" %} {% load static %} {% block content %}

<main>
  <div class="album py-5 bg-transparent">
    <div class="container bg-transparent">
      <div class="pb-3 h5 bg-transparent">{{category.name|title}}</div>
      <div class="products-container bg-transparent">
        {% for product in products %}
        <div class="col bg-transparent">
          <div class="card shadow-sm bg-transparent">
            <div class="flip-card">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <img
                    class="card-img-top first-img"
                    alt="Responsive image"
                    src="{{ product.image.url }}"
                  />
                </div>
                <div class="flip-card-back">
                  <img
                    class="card-img-top second-img"
                    alt="Responsive image"
                    src="{{ product.image2.url }}"
                  />
                </div>
              </div>
            </div>

            <div class="card-body">
              <p class="card-text">
                <a
                  class="text-dark text-decoration-none bolder-text"
                  href="{{ product.get_absolute_url }}"
                  >{{ product.title }}</a
                >
                <svg
                  id="svg{{forloop.counter}}"
                  class="bi bi-bookmark-fill"
                  data-index="{{product.id}}"
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  fill="currentColor"
                  viewBox="0 0 16 16"
                >
                  <path
                    d="M2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2z"
                  ></path>
                </svg>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{ product.brand }}</small>
                {%if result == 'yes'%}
                <small class="text-muted"
                  ><strong>&pound;<s>{{ original.price }}</s>{{product.price|floatformat:2}}</strong></small
                >
                {% else %}
                <small class="text-muted"
                ><strong>&pound;{{ product.price }}</strong></small
              >
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <script>

          {% if product.is_wishlisted %}
            $("#svg{{forloop.counter}}").css("color","red");
          {% endif %}
        </script>
        {% endfor %}
      </div>
    </div>
  </div>
</main>
<script>
  $(document).on("click", ".bi-bookmark-fill", function (e) {
    e.preventDefault();
    console.log("success-step1");
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "saved:saved" %}',
      data: {
        productid: $(this).data("index"),

        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        console.log(json.status);
        if (json.status) {
          $('[data-index="' + prodid + '"]').css("color", "red");
        } else {
          $('[data-index="' + prodid + '"]').css("color", "white");
        }

        console.log("success-step2");
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>
{% endblock %}

templates/store/collections.html
{% extends '../base.html' %}
{% load static %}
{%block content%}

<main>
    <div class="album py-5 bg-transparent">
      <div class="container bg-transparent">
  
        <div class="pb-3 h5 bg-transparent ">wishlist</div>
        <div class="products-container bg-transparent">
  
        {% for product in products %}
  
          <div class="col bg-transparent">
            <div class="card shadow-sm bg-transparent">
          
              <div class="flip-card">
                <div class="flip-card-inner">
                  <div class="flip-card-front">
                    <img class="card-img-top first-img" alt="Responsive image" src="{{ product.image.url }}">
                  </div>
                  <div class="flip-card-back">
                    <img class="card-img-top second-img" alt="Responsive image" src="{{ product.image2.url }}">
                  </div>
                </div>
              </div>
            
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none bolder-text" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                  <svg id="svg{{forloop.counter}}" class="bi bi-bookmark-fill" data-index="{{product.id}}" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"  viewBox="0 0 16 16"> <path d="M2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2z" ></path> </svg>
                  
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">{{ product.brand }}</small>
                  <small class="text-muted"><strong>&pound;{{ product.price }}</strong></small>
                </div>
              </div>
            </div>
          </div>
          <script>   
            {% if product.is_wishlisted %}
              $("#svg{{forloop.counter}}").css("color","red");
              console.log('half-sucess');
            {% endif %}
          </script> 
        {% endfor %}
  
        </div>
      </div>
    </div>
  
  
  </main>
  <script>
    $(document).on('click', '.bi-bookmark-fill', function (e) {
      e.preventDefault();
      console.log('success-step1');
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "saved:saved" %}',
        data: {
          productid: $(this).data('index'),
          
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          console.log(json.status);
          if(json.status){
            $('[data-index="'+prodid+'"]').css("color","red");
          }
          else{
            location.reload();
          }
          
          console.log('success-step2');
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  </script>
{% endblock %}

templates/store/contactus.html
{%extends '../base.html'%}

{%block content%}
<div class="registered-msg-div">
    <h1 class="heading-font-style">Contact Details</h1>
    <hr />
    <p>You can use the following information to know more about me and my work. And you can also contact me using the email provided at the bottom:
        <hr />
        <ul>
            <li><img src="https://img.icons8.com/ios/50/null/internet--v1.png"/>  : <a href="https://jayesh-khairnar.netlify.app/"> https://jayesh-khairnar.netlify.app/</a></li>
            <li><img src="https://img.icons8.com/ios-filled/50/null/github.png"/> : <a href="https://github.com/Jayesh-Ru"> https://github.com/Jayesh-Ru</a></li>
            <li><img src="https://img.icons8.com/ios-filled/50/null/linkedin-2--v1.png"/> : <a href="https://www.linkedin.com/in/jayesh-khairnar-0b5735207/">https://www.linkedin.com/in/jayesh-khairnar-0b5735207/</a></li>
            <li><img src="https://img.icons8.com/fluency/48/null/gmail.png"/> : <a href="mailto:rockykhairnar2099@gmail.com">rockykhairnar2099@gmail.com</a></li>
        </ul>
    </p>
</div>

{%endblock%}

templates/store/index.html
{% extends "../base.html"%}
{% load static%}
{% comment %} {%block title %}ClothingStore{% endblock %} {% endcomment %}

{% block content%}
<main>
  <div class="slider">
    <div class="slider__content">
      <img src="{% static 'images/ZANEROBE-3-4-Puffer-Home_2700x.jpg' %}" alt="image2"/>
      <div class="slider__description">
        <h1>New Arrivals</h1>
        <p>
          The newest fashion in town 
        </p>
        <a href="{% url "store:new_arrival"%}">Know More</a>
      </div>
    </div>
  </div>
    
    <div class="outer-container">
  
      <div class="h5">"Fashions fade, style is eternal." —<i>Yves Saint Laurent</i></div>
        <div class="main-container">
  
          {% for c in categories %}
  
          <div class="categories-container">
            <div class="categories-list">
              <img class="img"  alt="Responsive image" src="{{ c.category_image.url }}">
              <div class="custom-card-body" >
                <p class="custom-card-text" >
                  <a class="text-dark text-decoration-none" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                </p>
                {% comment %} <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">9min read</small>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
  
          {% endfor %}
  
        </div>

        
          
        
      </div>
    </div>
    

  
  </main>
  

{% endblock %}

templates/store/new_arrivals.html
{%extends '../base.html'%}

{%block content%}
<div class="new-arrival">
    <h1>NEW ARRIVALS<br> AROUND THE CORNER</h1>
    <h2> stay tuned</h2>
    <div class="arrow bounce">
    <a class="fa fa-arrow-down" href="#"></a>
    </div>
    <section class="button-new-arrival">
    <div class="searchBox">
    <input class="searchInput"type="email" name="" placeholder="Email address*" required="">
    <button class="searchButton" href="#">Notify Me</button>
    </div>
    </section>
    
</div>
<script>
    {% comment %} Make csrf token availble in JS files {% endcomment %}
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>
{%endblock%}

templates/store/single.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
                <hr class="bg-transparent">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image2.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <hr>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6 heading-font-style">{{product.brand}}</div>
                            {%if result == 'yes'%}
                            <div class="col-6 text-end"><span class="h4 fw-bold">£<s>{{ original.price }}</s> {{ product.price|floatformat:2 }}</span></div>
                            {%else%}
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                            {%endif%}
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                        <div class="col-6 text-end">
                            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Add to basket</button>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script>
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function (json) {
                   document.getElementById('basket-qty').innerHTML= json.qty
                },
                error: function (xhr, errmsg, err) {}
            });
        })
    </script>
</div>
{% endblock %}

templates/store/subscribe_section.html
{% extends '../base.html'%}
{%load static%}
{%block content%}

<div class="sub-div">

    <img src="{% static 'images/sale-offer-photo.jpg' %}"/>
    <div class="sub-desc">
        <h3 class="heading-font-style">Subscribe Section</h3>
        <p> You stand to earn a full discount of 10% on all of the orders if you are a subscriber.
            And all you need to do is click on the subscribe button below.</p>
        <div class="box">
                <div class="header"><i class="fa bg-transparent fa-paper-plane" aria-hidden="true"></i>
                  <p class="hidden">Thanks!</p>
                </div>
                <div class="form">
                {% csrf_token %}
                <input type="text" placeholder="Your Email" class="field">
                <input type="button" value="Subscribe" class="button">
                </div>
        </div>
        
    </div>
</div>
<script>
    {% comment %} Make csrf token availble in JS files {% endcomment %}
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>

{%endblock%}